---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: botbot-demo
  namespace: botbot
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:v*
spec:
  releaseName: botbot-demo
  chart:
    git: git@github.com:tuanat2359media/k8s
    ref: master
    path: charts/xregex-cloud
  values:
    replicas:
      worker: 1
      server: 3
      client: 1
